@startuml Cart
class Cart {
  +_id: ObjectId
  +user_id: ObjectId {ref: 'User', unique}
  +voucher_id: ObjectId {ref: 'Voucher'}
  +subtotal: Number
  +shipping_fee: Number
  +discount_amount: Number
  +total_amount: Number
  +createdAt: Date
  +updatedAt: Date
}
@enduml