@startuml ComboProduct
class ComboProduct {
  +_id: ObjectId
  +combo: ObjectId {ref: 'Combo'}
  +product: ObjectId {ref: 'Product'}
  +quantity: Number
  +created_by: ObjectId {ref: 'User'}
  +createdAt: Date
  +updatedAt: Date
}
@enduml