@startuml Product
class Product {
  +_id: ObjectId
  +name: String
  +description: String
  +price: Number
  +imageUrl: String
  +category: String
  +created_by: ObjectId {ref: 'User'}
  +createdAt: Date
  +updatedAt: Date
}
@enduml