@startuml User
class User {
  +_id: ObjectId
  +fullName: String
  +email: String {unique}
  +password: String
  +phone: String {unique}
  +address: String
  +role: String {enum: ['admin', 'user']}
  +googleId: String
  +createdAt: Date
  +updatedAt: Date
}
@enduml